general {
  disable_loading_bar = true
  hide_cursor = true
  no_fade_in = true
  no_fade_out = true
  ignore_empty_input = true
}

background {
  monitor =
  path = ~/.config/hypr/wallpaper_effects/.wallpaper_current
  # path = ~/.cache/hyde/wall.set
  blur_passes = 1
  contrast = 0.8916
    brightness = 0.7172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# Day
label {
  monitor =
  text = cmd[update:1000] echo -e "$(date +"%A" | awk '{print toupper($0)}' )" | sed 's/\(.\)/\1 /g' 
    color = $wallbash_txt2_rgba
    font_size = 80
    font_family = Anurati Bold
    # position = 0, 200
    position = 0%, 20%
    halign = center
    valign = center
}

#Time
label {
    monitor =
    text = cmd[update:100] echo -e "<b>$(date +"%H:%M:%S")</b>"
    font_size = 80
    color = $wallbash_txt1_rgba
    font_family = tty clock
    position = 0, 11%
    halign = center
    valign = center
}


input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.2 
    dots_spacing = 1.00
    dots_center = true
    outer_color = $wallbash_txt2_rgba
    inner_color = $wallbash_pry2_rgba
    font_color = $wallbash_3xa9_rgba
    capslock_color = rgba(255, 0, 0)
    fade_on_empty = true
    fade_timeout = 1000
    hide_input = false
    # position = 0, 100
    position = 0%, 5%
    check_color = $wallbash_pry4_rgba
    fail_color = rgba(FF0000FF) # if authentication failed, changes outer_color and fail message color
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i> 
    fail_transition = 300 # transition time in ms between normal outer_color and fail_color
    swap_font_color = true
    halign = center
    valign = bottom
}
