# Default Keybinds
# visit https://wiki.hyprland.org/Configuring/Binds/ for more info

# /* ---- ✴️ Variables ✴️ ---- */  #
$mainMod = SUPER
$scriptsDir = $HOME/.config/hypr/scripts
$UserConfigs = $HOME/.config/hypr/UserConfigs
$UserScripts = $HOME/.config/hypr/UserScripts

bind = $mainMod, Q, killactive, # close active (not kill)
bind = $mainMod SHIFT, Q, exec, $scriptsDir/KillActiveProcess.sh # Kill active process

# Dwindle Layout
bind = $mainMod SHIFT, I, togglesplit # only works on dwindle layout
bind = $mainMod, P, pseudo, # dwindle

# group
bind = $mainMod CTRL, tab, changegroupactive  # change focus to another window

# Cycle windows if floating bring to top
bind = ALT, tab, cyclenext
bind = ALT, tab, bringactivetotop  
# bind = ALT SHIFT, Tab, cyclenext, prev
# bind = ALT SHIFT, Tab, bringactivetotop,

# Special Keys / Hot Keys
bindl = , xf86Sleep, exec, systemctl suspend  # sleep button 
bindl = , xf86Rfkill, exec, $scriptsDir/AirplaneMode.sh # Airplane mode

# Swap windows
bind = CTRL ALT, left, swapwindow, l
bind = CTRL ALT, right, swapwindow, r
bind = CTRL ALT, up, swapwindow, u
bind = CTRL ALT, down, swapwindow, d

# Workspaces related
bind = $mainMod, tab, workspace, r+1 
bind = $mainMod SHIFT, tab, workspace, r-1 

# Special workspace
bind = $mainMod SHIFT, U, movetoworkspace, special
bind = $mainMod, U, togglespecialworkspace,
