#   #
#Commands & Apps to be executed at launch

$scriptsDir = $HOME/.config/hypr/scripts
$UserScripts = $HOME/.config/hypr/UserScripts

$wallDIR=$HOME/Pictures/wallpapers
$lock = $scriptsDir/LockScreen.sh
$SwwwRandom = $UserScripts/WallpaperAutoChange.sh

# wallpaper stuff / More wallpaper options below
exec-once = swww-daemon --format xrgb
#exec-once = $SwwwRandom $wallDIR # random wallpaper switcher every 30 minutes

# Startup
# exec-once = systemctl --user start wallust-manager.service
# exec-once = systemctl --user start easyeffects-manager.service
# exec-once = systemctl --user start waybar-manager.service

# Polkit (Polkit Gnome / KDE)
exec-once = $scriptsDir/Polkit.sh

# Startup Scripts (Really Important for some functionalities don't comment out !!! Unless already commented out)
exec-once = zsh -c "~/.config/hypr/scripts/Brightness.sh --rs"
exec-once = zsh -c "~/.config/hypr/scripts/Easyeffects-watcher.sh"
exec-once = zsh -c "~/.config/hypr/scripts/Waybar-watcher.sh"
exec-once = zsh -c "~/.config/hypr/scripts/Lid-watcher.sh"
# exec-once = zsh -c "~/.config/hypr/scripts/Wallust-watcher.sh"

# starup apps
exec-once = ags &
#exec-once = rog-control-center &

#clipboard manager
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Rainbow borders
exec-once = $UserScripts/RainbowBorders.sh &

# G00380316
exec-once = kitty --start-as=fullscreen 
# exec-once = zsh -c "ollama serve"
# exec-once = XDG_SESSION_TYPE=x11 bluemail --force-device-scale-factor=1.5

# Here are list of features available but disabled by default
#gnome polkit for nixos
#exec-once = $scriptsDir/Polkit-NixOS.sh

# xdg-desktop-portal-hyprland (should be auto starting. However, you can force to start)
#exec-once = $scriptsDir/PortalHyprland.sh

