#   
# /* wallust template - colors-hyprland */ 

$background = rgb(1F1F1F)
$foreground = rgb(CCCCCC)
$color0 = rgb(454545)
$color1 = rgb(232222)
$color2 = rgb(402548)
$color3 = rgb(46334B)
$color4 = rgb(4D4D4D)
$color5 = rgb(504E50)
$color6 = rgb(515151)
$color7 = rgb(ADADAD)
$color8 = rgb(797979)
$color9 = rgb(2E2D2E)
$color10 = rgb(563160)
$color11 = rgb(5D4364)
$color12 = rgb(676767)
$color13 = rgb(6B686B)
$color14 = rgb(6C6C6C)
$color15 = rgb(ADADAD)
