$HOME/.config/hypr/themes/theme.conf|> $HOME/.config/hypr/themes/colors.conf

$SDDM_THEME=MacOS
$GTK_THEME=MacOS
$ICON_THEME=MacOS
$CURSOR_THEME=MacOS-Cursor

exec = gsettings set org.gnome.desktop.interface icon-theme '$ICON_THEME'
exec = gsettings set org.gnome.desktop.interface gtk-theme '$GTK_THEME'
exec = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

# // You can use the commands below or use the HyDE CLI to set the cursor globally
# exec = gsettings set org.gnome.desktop.interface cursor-theme '$CURSOR_THEME'
# exec = gsettings set org.gnome.desktop.interface cursor-size 20
# exec = hyprctl setcursor MacOS-Cursor 20
exec = Hyde cursor theme '$CURSOR_THEME' size 30

# // Set the sddm theme here
exec = Hyde sddm set $SDDM_THEME

general {
    gaps_in = 6
    gaps_out = 12
    border_size = 3
    col.active_border = rgba(78c6ebff) rgba(8289a3ff) 45deg
    col.inactive_border = rgba(7, 15, 42, 0.58)
    layout = dwindle
    resize_on_border = true
}

decoration {
    rounding = 2
    drop_shadow = false

    blur {
        enabled = yes
        size = 4
        passes = 2
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
}

blurls = waybar

