#!      ░▒▒▒░░░▓▓           ___________
#!    ░░▒▒▒░░░░░▓▓        //___________/
#!   ░░▒▒▒░░░░░▓▓     _   _ _    _ _____
#!   ░░▒▒░░░░░▓▓▓▓▓▓ | | | | |  | |  __/
#!    ░▒▒░░░░▓▓   ▓▓ | |_| | |_/ /| |___
#!     ░▒▒░░▓▓   ▓▓   \__  |____/ |____/
#!       ░▒▓▓   ▓▓  //____/

# $LOCKSCREEN = hyprlock # preferred LOCKSCREEN e.g swaylock
$LOCKSCREEN = lockscreen.sh # Calls $LOCKSCREEN set from hyprland

general {
    lock_cmd = $LOCKSCREEN
    unlock_cmd = #notify-send "unlock!"
    before_sleep_cmd = # no need, locking is handled by script
    after_sleep_cmd = #notify-send "Awake!"
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
}

# Dims the display
listener {
    timeout = 60
    on-timeout = { brightnessctl -s && brightnessctl s 1% ;}
    on-resume = brightnessctl -r
}

# Lock screen after 2 mins
listener {
    timeout = 120
    on-timeout = $LOCKSCREEN
}

# DPMS off after 5 mins
listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl reload
}

# Suspend after 10 mins, but safely
listener {
    timeout = 600
    on-timeout = systemctl suspend
}
