source = ~/.config/hyprlock/theme.conf
general {
  disable_loading_bar = true
  hide_cursor = true
  no_fade_in = true
  no_fade_out = true
  ignore_empty_input = true
}

background {
  monitor =
  # path = ~/.config/hypr/wallpaper_effects/.wallpaper_current
  path = ~/.cache/hyde/wall.set
  blur_passes = 1
  contrast = 0.8916
    brightness = 0.7172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# Day
label {
  monitor =
  text = cmd[update:1000] echo -e "$(date +"%A" | awk '{print toupper($0)}' )" | sed 's/\(.\)/\1 /g' 
    color = $color13
    font_size = 80
    font_family = Anurati Bold
    position = 0, 0
    halign = center
    valign = center
}

#Time
label {
    monitor =
    text = cmd[update:100] echo -e "<b>$(date +"%H:%M:%S")</b>"
    font_size = 80
    color = $color12
    font_family = tty clock
    position = 0, -720
    halign = center
    valign = top
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.2 
    dots_spacing = 1.00
    dots_center = true
    outer_color = $color11
    inner_color = rgba(255, 255, 255, 0.1)
    font_color = $color13
    capslock_color = rgba(255, 0, 0)
    fade_on_empty = true
    fade_timeout = 1000
    hide_input = false
    position = 0, 100
    fail_color = rgb(204, 34, 34) 
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i> 
    fail_transition = 100 
    swap_font_color = false
    halign = center
    valign = bottom
}